FROM node as build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ARG REACT_APP_ENV
ENV REACT_APP_ENV=$REACT_APP_ENV
ARG REACT_APP_BASE_URL
ENV REACT_APP_BASE_URL=$REACT_APP_BASE_URL
RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html