version: "3"
services:
  react-app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_ENV=production
        - REACT_APP_BASE_URL=https://students-sample-1a.herokuapp.com
    ports:
      - "8081:80"
    env_file:
      - ./.env.prod